"""Small policy checks for ordinary pull requests.

Release records are generated by explicit release commands, so ordinary PRs
must not edit the manifest, changelog, citation version, or release fragments.
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import Iterable


_CITATION_VERSION_RE = re.compile(r"(?m)^version\s*:\s*([^\r\n#]+?)\s*(?:#.*)?$")


def check_release_policy(base_root: Path, head_root: Path, changed_paths: Iterable[str]) -> list[str]:
    """Return policy violations without reading ``release.toml`` or fragments."""
    paths = sorted({path.removeprefix("./") for path in changed_paths if path})
    errors: list[str] = []
    if "CHANGELOG.md" in paths:
        errors.append("Ordinary PRs must not edit generated CHANGELOG.md")
    if "build/release_manifest.json" in paths:
        errors.append("Ordinary PRs must not edit generated build/release_manifest.json")
    if "release.toml" in paths:
        errors.append("release.toml is obsolete; release inputs come from schemas, PRs, and the chosen bundle version")
    if any(path.startswith(".changes/") for path in paths):
        errors.append("Release fragments under .changes/ are obsolete")
    if "CITATION.cff" in paths:
        base = base_root / "CITATION.cff"
        head = head_root / "CITATION.cff"
        if base.is_file() and head.is_file():
            old = _CITATION_VERSION_RE.findall(base.read_text(encoding="utf-8"))
            new = _CITATION_VERSION_RE.findall(head.read_text(encoding="utf-8"))
            if len(old) != 1 or len(new) != 1:
                errors.append("CITATION.cff must contain exactly one top-level version field")
            elif old[0].strip() != new[0].strip():
                errors.append("Ordinary PRs must not change the top-level CITATION.cff version")
    return errors
