"""Small policy checks for ordinary pull requests.

Release records are generated by explicit release commands, so ordinary PRs
must not edit existing manifests, changelog entries, citation versions, or
release fragments.
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import Iterable


_CITATION_VERSION_RE = re.compile(r"(?m)^version\s*:\s*([^\r\n#]+?)\s*(?:#.*)?$")
_UNRELEASED_RE = re.compile(r"(?m)^##\s+\[Unreleased\]\s*$")
_RELEASE_HEADING_RE = re.compile(r"(?m)^##\s+\[(?!Unreleased\])[^\]\r\n]+\](?:\s+-.*)?\s*$")


def check_release_policy(base_root: Path, head_root: Path, changed_paths: Iterable[str]) -> list[str]:
    """Return policy violations without reading ``release.toml`` or fragments."""
    paths = sorted({path.removeprefix("./") for path in changed_paths if path})
    errors: list[str] = []
    if "CHANGELOG.md" in paths:
        base_changelog = base_root / "CHANGELOG.md"
        head_changelog = head_root / "CHANGELOG.md"
        if base_changelog.is_file():
            base_text = base_changelog.read_text(encoding="utf-8")
            head_text = head_changelog.read_text(encoding="utf-8") if head_changelog.is_file() else ""
            has_previous_release = (base_root / "build/release_manifest.json").is_file()
            if has_previous_release:
                errors.append("Ordinary PRs must not edit generated CHANGELOG.md")
            elif not _UNRELEASED_RE.search(base_text) or not _UNRELEASED_RE.search(head_text):
                errors.append("Pre-release CHANGELOG.md edits require an ## [Unreleased] section")
            elif _RELEASE_HEADING_RE.search(base_text) or _RELEASE_HEADING_RE.search(head_text):
                errors.append("Ordinary PRs must not add generated release sections to CHANGELOG.md")
        else:
            head_text = head_changelog.read_text(encoding="utf-8") if head_changelog.is_file() else ""
            if not _UNRELEASED_RE.search(head_text):
                errors.append("Initial CHANGELOG.md must contain an ## [Unreleased] section")
            elif _RELEASE_HEADING_RE.search(head_text):
                errors.append("Ordinary PRs must not add generated release sections to CHANGELOG.md")
    if "build/release_manifest.json" in paths:
        errors.append("Ordinary PRs must not edit generated build/release_manifest.json")
    if "release.toml" in paths:
        errors.append("release.toml is obsolete; release inputs come from schemas, PRs, and the chosen bundle version")
    if any(path.startswith(".changes/") for path in paths):
        errors.append("Release fragments under .changes/ are obsolete")
    if "CITATION.cff" in paths:
        base = base_root / "CITATION.cff"
        head = head_root / "CITATION.cff"
        if base.is_file() and head.is_file():
            old = _CITATION_VERSION_RE.findall(base.read_text(encoding="utf-8"))
            new = _CITATION_VERSION_RE.findall(head.read_text(encoding="utf-8"))
            if len(old) != 1 or len(new) != 1:
                errors.append("CITATION.cff must contain exactly one top-level version field")
            elif old[0].strip() != new[0].strip():
                errors.append("Ordinary PRs must not change the top-level CITATION.cff version")
    return errors
